"""add indexes for ticket filters

Revision ID: 18a8c43e6ea2
Revises: 9bf91b698b13
Create Date: 2025-08-15 18:33:31.792347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a8c43e6ea2'
down_revision: Union[str, Sequence[str], None] = '9bf91b698b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tickets_assignee_id', 'tickets', ['assignee_id'], unique=False)
    op.create_index('ix_tickets_status', 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_status', table_name='tickets')
    op.drop_index('ix_tickets_assignee_id', table_name='tickets')
    # ### end Alembic commands ###
